name: vision media
favicon: null
layout_spectrum: 0.01662684208713472
typography_spectrum: 0.7853614126797765
title: wo this is shit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d140f'
    - '#5e391f'
    - '#ada694'
    - '#8f643a'
  brandStrength: 0.7894987456966192
  lightness: 0.5651015108451247
  saturation: 0.18269054032862186
  rhythmicContrast: 0.23673308151774108
purpose: []
